logging:
  level:
    ROOT: INFO
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        security: TRACE
    com:
      jiwhiz: DEBUG


spring:
  application:
    version: local-snapshot
  jpa:
    properties:
      hibernate:
        format_sql: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/mydoctordemo
    username: walle
    password: walle
    hikari:
      poolName: Hikari
      auto-commit: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.mydoctor:8080/realms/mydoctor-demo
          jwk-set-uri: http://auth.mydoctor:8080/realms/mydoctor-demo/protocol/openid-connect/certs
      client:
        registration:
          myhealth-auth-client:
            client-id: mydoctor-api-server
            authorization-grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
            provider: myhealth-auth-provider
          mydoctor-auth-client:
            client-id: mydoctor-api
            client-secret: nvYxjQFYGdNI8zj5Nb3Jz25ezWgN1cE8
            client-authentication-method: client_secret_basic
            authorization-grant-type: urn:ietf:params:oauth:grant-type:token-exchange
            provider: mydoctor-auth-provider
        provider:
          myhealth-auth-provider:
            token-uri: http://auth.myhealth:8090/realms/myhealth-demo/protocol/openid-connect/token
          mydoctor-auth-provider:
            token-uri: http://auth.mydoctor:8080/realms/mydoctor-demo/protocol/openid-connect/token
  ai:
    ollama:
      base-url: http://localhost:11434/
      chat:
        enabled: true
        options:
          model: 'llama3.2'
      embedding:
        enabled: true
        options:
          model: 'nomic-embed-text'
    vectorstore:
      weaviate:
        host: localhost:8050
        api-key: ""
        scheme: http


server:
  port: 8081

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    tagsSorter: alpha
    operationsSorter: alpha


app:
  my-health:
    api-base-url: 'http://api.myhealth:8082/api/v1'
  security:
    oauth2:
      audience:
        - mydoctor-ui
  cors:
    # Allow local angular web server
    allowed-origins:
      - 'http://ui.mydoctor:1234'
    # Enable CORS when running in GitHub Codespaces
    allowed-origin-patterns: 'https://*.githubpreview.dev'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${spring.application.name}-alert,X-${spring.application.name}-error,X-${spring.application.name}-params'
    allow-credentials: true
    max-age: 1800

