services:
  postgres:
    image: postgres:16-alpine
    container_name: postgresql_db_local_dev
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d/
